---
go_tarball: "go1.9.3.linux-amd64.tar.gz"
go_download_location: "https://dl.google.com/go/{{ go_tarball }}"
go_tarball_checksum: "sha256:a4da5f4c07dfda8194c4621611aeb7ceaab98af0b38bfb29e1be2ebb04c3556c"
go_version_target: "go version go1.9.3 linux/amd64"
set_go_path: false
